# Site settings
title: material-jekyllize
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 Fractal. A global cryptocurrency
baseurl: "/material-jekyllize/" # the subpath of your site, e.g. /blog/
url: "http://irontiga.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  irontiga

# Build settings
markdown: kramdown