# Site settings
title: material-jekyllize
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 A materialize theme for jekyll
baseurl: "/material-jekyllize" # the subpath of your site, e.g. /blog/
url: "http://irontiga.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  irontiga

# Build settings
markdown: kramdown

paginate: 2
paginate_path: "/blog/page/:num"

permalink: "/blog/:year/:month/:day/:title/"

nav-groups:
 - group: "nav"
   subgroups:
    - group: "docs"
      title: "Documentaion"
      subgroups:
       - group: "getting-started"
         title: "Getting started"
       - group: "api"
         title: "API"