# Site settings
title: material-jekyllize
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
 A materialize theme for jekyll
baseurl: "/material-jekyllize" # the subpath of your site, e.g. /blog/
url: "http://irontiga.com" # the base hostname & protocol for your site
twitter_username: 
github_username:  irontiga

# Build settings
markdown: kramdown

paginate: 2
paginate_path: "/blog/page/:num"

permalink: "/blog/:year/:month/:day/:title/"


docs: &docs 
  group: "docs"
  title: "Docs"
  url: "/docs/"
  subgroups:
   - group: "getting-started"
     title: "Getting started"
     url: "/getting-started/"
   - group: "api"
     title: "API"
     url: "/api/"


nav-groups:
 - group: "nav"
   subgroups:
    - *docs